### PR TITLE
Add the entry point to the image

### PR DESCRIPTION
**Pull request by CorcovadoMing**
Able to launch a container just by `docker run -it <image>`

### CODE REVIEW

**Comment by petrosagg** [comment]
Hi @CorcovadoMing, unfortunately this change will break the image when you try to run it on an actual ARM target

**Comment by CorcovadoMing** [comment]
@petrosagg Is it possible to make a conditional script that assigns different entry points for different architectures?

**Comment by petrosagg** [comment]
Not that I'm aware of. When docker starts a container it ultimately does a `execve()` syscall with some executable in there. So the only something like this could work would be an executable that is both ARM and x86 at the same time.

**Comment by CorcovadoMing** [comment]
@petrosagg Thanks for the explanation, it seems to be difficult, I'll close this PR since I didn't considering running on other targets

**Pull request closed without merging**
